### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by tpluscode** [un-ts/changesets-gitlab#109]
We are using changesets-gitlab without publishing

It would be very useful if the repository got tagged when the "Version Packages" MR is merged

**Comment by pascal-sochacki** [comment]
Hey, you can hack it by just adding the env: `NPM_TOKEN` (the value is not relevant) and setting the `INPUT_PUBLISH` to `yarn changeset publish`.

The complete Job looks like this in my Repository: 

```
release:
  image: node:18.11
  stage: release
  variables:
    GITLAB_HOST: https://xxxxxx
    GITLAB_CI_USER_NAME: "xxxxxxx"
    INPUT_PUBLISH: yarn changeset publish
    NPM_TOKEN: dummy
  only: 
    - main
  script:
    - yarn changesets-gitlab
```

Sure, it would be better without the dummy value and some docs

**Comment by meesvandongen** [comment]
Not exactly this issue, but I will just leave this here for future reference; the creation of git tags depends using `@changesets/cli`. So you cannot use e.g. `pnpm publish -r --no-git-checks` in the `INPUT_PUBLISH` variable -- you must use `changeset publish`. Also, the creation of releases depends on the creation of tags.

**Comment by n1kk** [comment]
Not exactly same issue but I'll leave it here for other who get here from google. 

I needed to version a package without publishing, but the private packages where not tagged in the git. I tried to switch `INPUT_PUBLISH: changeset publish` to `INPUT_PUBLISH: changeset version && changeset tag` but this package is not executing it as a shell like, it executes the line as a single command so I get an error `too many arguments` from `changeset`.

What evenrually worked was to save the script in `.sh` file and execute it with bash:

```sh
# publish .sh
changeset version
changeset tag
git push origin --tags
```

```yaml
release:
  variables:
    INPUT_PUBLISH: bash ./publish.sh
  script:
    - changesets-gitlab
```
