### ISSUE TITLE
Response code 401 (Unauthorized)  code: 'ERR_NON_2XX_3XX_RESPONSE',

### ISSUE THREAD

**Issue by Wxh16144** [un-ts/changesets-gitlab#112]
I tried a lot of solutions, but in the end they didn't work. Can you help me?

**.gitlab-ci.yml**

```yml
stages:
  - install
  - lint
  - comment
  - release

image: node:16.20.0

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - "**/node_modules/"
    - node_modules/

before_script: &global_before_script
  - corepack enable
  - corepack prepare pnpm@latest-7 --activate
  - pnpm config set store-dir .pnpm-store

install:
  stage: install
  before_script:
    - *global_before_script
    - pnpm config set registry https://registry.npmmirror.com/
  script:
    - pnpm install # install dependencies
  tags:
    - builder-wxh
  only: &common_only
    - master
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - merge_requests

lint:
  stage: lint
  script:
    - npm run lint # lint code
  only: *common_only
  tags:
    - builder-wxh

pre_compile:
  stage: lint
  tags:
    - builder-wxh
  script:
    - npm run build # compile code
  only: *common_only

comment:
  stage: comment
  tags:
    - builder-wxh
  only:
    - merge_requests
  # comment automatically like https://github.com/changesets/bot
  script: pnpm dlx changesets-gitlab comment

create_MR:
  stage: release
  tags:
    - builder-wxh
  when: manual
  variables:
    GITLAB_TOKEN: $CI_JOB_TOKEN
    INPUT_PUBLISH: npm run build
    INPUT_TITLE: "chore(release): publish"
    TARGET_BRANCH: refactor # TODO: change to master
  script:
    - |
      cat << EOF > "$HOME/.npmrc"
        email = wuxiaohong@aquilatech.ai
        //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
      EOF
    - echo "Created the following .npmrc:"; cat "$HOME/.npmrc"
    - pnpm dlx changesets-gitlab
  only: *common_only
  except:
    - merge_requests

```

<details><summary>logs</summary>
<p>

[0KRunning with gitlab-runner 16.0.2 (85586bd1)[0;m
[0K  on builder-wxh _5z-vVyu6, system ID: s_6965a954eb78[0;m
section_start:1691047484:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image node:16.20.0 ...[0;m
[0KPulling docker image node:16.20.0 ...[0;m
[0KUsing docker image sha256:c56ec223ce193f5e085a073b727aa63e01f1d31f9d9b5baddab4523389db5f6d for node:16.20.0 with digest node@sha256:07ac708c46cc7136db9d54749c541ba1dc516dc316e126a94136083b842c2db9 ...[0;m
section_end:1691047487:prepare_executor
[0Ksection_start:1691047487:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-5z-vvyu6-project-31-concurrent-0 via szq-ubuntu...
section_end:1691047488:prepare_script
[0Ksection_start:1691047488:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/common-editor-toolkit/editor/.git/
[32;1mChecking out 263b27a5 as detached HEAD (ref is feature/ci)...[0;m
Removing .pnpm-store/
Removing node_modules/
Removing packages/browser/node_modules/
Removing packages/components-pro/node_modules/
Removing packages/components/node_modules/
Removing packages/core/node_modules/
Removing packages/desktop/node_modules/
Removing playground/node_modules/

[32;1mSkipping Git submodules setup[0;m
section_end:1691047491:get_sources
[0Ksection_start:1691047491:restore_cache
[0K[0K[36;1mRestoring cache[0;m[0;m
[32;1mChecking cache for 0_pnpm-lock-91d8e5d408686549482d3a90dde9877a734df4bb-non_protected...[0;m
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.[0;m 
[0;33mWARNING: node_modules/.pnpm/@ant-design+cssinjs@1.16.1_biqbaboplfbrettd7655fr4n2y/node_modules/react-dom/node_modules/: mkdir node_modules/.pnpm/@ant-design+cssinjs@1.16.1_biqbaboplfbrettd7655fr4n2y/node_modules/react-dom: file exists (suppressing repeats)[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1691047505:restore_cache
[0Ksection_start:1691047505:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:c56ec223ce193f5e085a073b727aa63e01f1d31f9d9b5baddab4523389db5f6d for node:16.20.0 with digest node@sha256:07ac708c46cc7136db9d54749c541ba1dc516dc316e126a94136083b842c2db9 ...[0;m
[32;1m$ corepack enable[0;m
[32;1m$ corepack prepare pnpm@latest-7 --activate[0;m
Preparing pnpm@latest-7 for immediate activation...
[32;1m$ pnpm config set store-dir .pnpm-store[0;m
[32;1m$ cat << EOF > "$HOME/.npmrc" # collapsed multi-line command[0;m
[32;1m$ echo "Created the following .npmrc:"; cat "$HOME/.npmrc"[0;m
Created the following .npmrc:
  email = wuxiaohong@aquilatech.ai
  //git.aquilainteractive.cn/api/v4/projects/31/packages/npm/:_authToken=[MASKED]
[32;1m$ pnpm dlx changesets-gitlab[0;m
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 1, reused 0, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 8, reused 8, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          |  WARN  deprecated @gitbeaker/node@35.8.1
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 20, reused 20, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 23, reused 23, downloaded 0, added 0
 WARN  GET https://registry.npmjs.org/@changesets%2Fread error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@sentry%2Fnode error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@changesets%2Ferrors error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 24, reused 23, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 25, reused 25, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 28, reused 28, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 44, reused 43, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 59, reused 59, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 92, reused 92, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 117, reused 117, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 153, reused 150, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 190, reused 190, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 226, reused 226, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 235, reused 235, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 239, reused 238, downloaded 0, added 0
../../.pnpm-store/v3/tmp/dlx-59          | +239 ++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /builds/.pnpm-store/v3
  Virtual store is at:             ../../.pnpm-store/v3/tmp/dlx-59/node_modules/.pnpm

::set-output name=published::false

::set-output name=publishedPackages::[]
setting git user
[command]/usr/bin/git config user.name Wu Xiaohong
[command]/usr/bin/git config user.email "gitlab[bot]@users.noreply.gitlab.com"
setting GitLab credentials
../../.pnpm-store/v3/tmp/dlx-59          | Progress: resolved 239, reused 239, downloaded 0, added 239, done
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/builds/.pnpm-store/v3/tmp/dlx-59/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1691047607638,
    socket: 1691047607639,
    lookup: 1691047607640,
    connect: 1691047607833,
    secureConnect: 1691047608278,
    upload: 1691047608278,
    response: 1691047608635,
    end: 1691047608641,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 1,
      tcp: 193,
      tls: 445,
      request: 0,
      firstByte: 357,
      download: 6,
      total: 1003
    }
  },
  description: '401 Unauthorized'
}
 ERROR  Command failed with exit code 1: /builds/.pnpm-store/v3/tmp/dlx-59/node_modules/.bin/changesets-gitlab

pnpm: Command failed with exit code 1: /builds/.pnpm-store/v3/tmp/dlx-59/node_modules/.bin/changesets-gitlab
    at makeError (/root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:22289:17)
    at handlePromise (/root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:22860:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (/root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:191714:7)
    at async /root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:199078:21
    at async run (/root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:199049:34)
    at async runPnpm (/root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:199270:5)
    at async /root/.cache/node/corepack/pnpm/7.9.5/dist/pnpm.cjs:199262:7
section_end:1691047609:step_script
[0Ksection_start:1691047609:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1691047609:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m

</p>
</details> 

[logs.txt](https://github.com/un-ts/changesets-gitlab/files/12248111/logs.txt)
