### ISSUE TITLE
When does changesets-gitlab create merge request? 

### ISSUE THREAD

**Issue by mborysenko** [un-ts/changesets-gitlab#115]
I have set up release job but without publishing step. Didn't add INPUT_PUBLISH var. Despite successful build the job doesn't create merge request.
Configuration looks like this:
```yaml
stages:
  - Publish

publish:
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
  stage: Publish
  when: manual
  script:
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> ~/.npmrc
    - yarn run changeset
  variables:
    INPUT_VERSION: yarn run version
    INPUT_COMMIT: "Version Packages"
    INPUT_TITLE: "Version Packages"
    GITLAB_HOST: $CI_REPOSITORY_URL
    GITLAB_TOKEN_TYPE: "job"
    GITLAB_TOKEN: $CI_JOB_TOKEN
    TARGET_BRANCH: "development"
    CREATE_GITLAB_RELEASES: "false"
    GITLAB_CI_USER_EMAIL: $GITLAB_USER_EMAIL
  needs:
    - job: install
      artifacts: true
    - job: build
      artifacts: true
```

package.json scripts:

```json
{
  "scripts": {
    "build": "rollup -c",
    "prerelease": "yarn build",
    "release": "changesets-gitlab publish",
    "changeset": "changesets-gitlab",
    "version": "changesets-gitlab version",
  }
}
```
