### ISSUE TITLE
Help: running a script to edit files in the merge request

### ISSUE THREAD

**Issue by pascal-sochacki** [un-ts/changesets-gitlab#126]
Hey, I want to write the version of the packages in my monorepo to an additional file. 

I have a (pnpm) Monorepo with 3 packages and I would like to change not only the package.json with the new version but also a file for the deployment of the new version. Is there a way to run a script with the new version? 

In the Readme I found 

> If you need to add additional logic to the version command, you can do so by using a version script.

> If the version script is present, this action will run that script instead of changeset version, so please make sure that your script calls changeset version at some point. All the changes made by the script will be included in the MR.

But i can't figure out what the "version script" is. I tried to write a "version" and a "update-versions" script in my package.json, but it seems as if it didn't run...

```json
...
 "scripts": {
    "version": "changeset version && echo 'test' > test",
    "update-versions": "changeset version && echo 'test' > test",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
...
```

Could anyone help me, please?

In my dreamworld, changeset-gitlab changes the versions in the packages, calls my custom script (where I can edit my file with the correct version from the package.json's) and after this, changeset-gitlab pushes all changes to the branch

**Comment by pascal-sochacki** [comment]
Nevermind, i'm found the solution:

gitlab ci:
```
release:
  image: node:18.11
  stage: release
  variables:
    INPUT_VERSION: yarn update-version <----- set input version env
    INPUT_PUBLISH: yarn changeset publish
  only: 
    - main
  script:
    - yarn changesets-gitlab
```
package.json
```
"scripts": {
    "update-version": "changeset version && echo 'test' > test" <----- run changeset version to change package jsons and then you can run a script  
  },

```

note: the script must be in the root of the monorepo.
