### ISSUE TITLE
comment adds new comment with every commit

### ISSUE THREAD

**Issue by maxkarkowski** [un-ts/changesets-gitlab#145]
since we updated changesets-gitlab we have now the issue that with every commit the changesets-gitlab comment command creates a new comment in our merge request. before the update it only created one comment for a merge request.

**Comment by JounQin** [comment]
Any screenshot?

cc @alan910127

**Comment by alan910127** [comment]
Hello @maxkarkowski, are you upgraded from v0.11.0 or v0.10.x? 
This information can help me locate the issue faster 😄

**Comment by maxkarkowski** [comment]
hey @alan910127 sorry of course i can. we are currently on version 0.10.3

**Comment by maxkarkowski** [comment]
> Any screenshot?
> 
> Should be related to #138 or #143(most likely)
> 
> cc @alan910127
here is a screenshot
![screen](https://github.com/un-ts/changesets-gitlab/assets/622841/a2f1c3d6-4eba-42f3-95a3-4637d82bde57)

**Comment by maxkarkowski** [comment]
> Any screenshot?
> 
> Should be related to #138 or #143(most likely)
> 
> cc @alan910127

here is a screenshot
![screen](https://github.com/un-ts/changesets-gitlab/assets/622841/ba025d65-271f-4d16-baa6-1c54d5addd13)

**Comment by maxkarkowski** [comment]
but even if there is a changeset found, new comment will appear with everey command run
<img width="1592" alt="SCR-20231128-idwj" src="https://github.com/un-ts/changesets-gitlab/assets/622841/b19f5f69-4180-490c-93b5-15c5aa277a2f">

**Comment by alan910127** [comment]
Hey @maxkarkowski, I couldn't reproduce the error on a project created on `gitlab.com`. Could you provide some information that might be related to this issue?

Here's something I think might be relevant:
- `CI_MERGE_REQUEST_IID` predefined variable
- [Discussions API](https://docs.gitlab.com/ee/api/discussions.html#merge-requests)

**Comment by idumancic** [comment]
@alan910127 I have the same problem, we are using a self-hosted instance of GitLab if that helps, but when I tested on `gitlab.com` I also did not get any error.

**Comment by maxkarkowski** [comment]
> @alan910127 I have the same problem, we are using a self-hosted instance of GitLab if that helps, but when I tested on `gitlab.com` I also did not get any error.

we are also using a self hosted gitlab

**Comment by maxkarkowski** [comment]
> Hey @maxkarkowski, I couldn't reproduce the error on a project created on `gitlab.com`. Could you provide some information that might be related to this issue?
> 
> Here's something I think might be relevant:
> 
> * `CI_MERGE_REQUEST_IID` predefined variable
> * [Discussions API](https://docs.gitlab.com/ee/api/discussions.html#merge-requests)

this is the comment job we have . it runs on every merge request 
```
comment:
  rules:
    - if: '$CI_MERGE_REQUEST_IID && $CI_COMMIT_BRANCH != "changeset-release/main"'
  extends:
    - .init-pnpm
  script:
    - pnpm changesets-gitlab comment # comment automatically like https://github.com/changesets/bot
    
.init-pnpm:
  before_script:
    - corepack enable
    - corepack prepare pnpm@8.5.1 --activate
    - node --max-old-space-size=8192
    - pnpm config set store-dir .pnpm-store
    - pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
 ```
