### ISSUE TITLE
.gitlab-ci.yml in example has syntax error

### ISSUE THREAD

**Issue by jaesoekjjang** [un-ts/changesets-gitlab#185]
Hi, i guess the current example of `.gitlab-ci.yml` has syntax errors

``` yml
stages:
  - comment
  - release

before_script: yarn --frozen-lockfile

comment:
  image: node:lts-alpine
  stage: comment 
  # only: merge_requests #fixed
  only:
    - merge_requests
  script: yarn changesets-gitlab comment

release:
  image: node:lts-alpine
  stage: release # added
  # only: main # fixed
  only: 
    - main
  script: yarn changesets-gitlab
  variables:
    INPUT_PUBLISH: yarn release
```

Fixing this way solved syntax errors for me. I can create a PR for this if you don't mind
