### ISSUE TITLE
`changesets-gitlab comment` is returning "404 Project Not Found"

### ISSUE THREAD

**Issue by trystendsmyth** [un-ts/changesets-gitlab#201]
This is the job setup in Gitlab CI (using Node 22):
```yml
changesets_comment:
  image: node:${NODE_VERSION}
  stage: comment
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pnpm changesets-gitlab comment
  variables:
    GITLAB_TOKEN_TYPE: job
    GITLAB_TOKEN: $CI_JOB_TOKEN
```

After `pnpm changesets-gitlab comment` is called in the job, the output is:
```
404 Project Not Found
request: 
The error's response could not be used as plain text
GitbeakerRequestError: Not Found
```

When I look at the URL it's like this:
`https://gitlab.com/api/v4/projects/<PROJECT_ID>/merge_requests/<MR_NUMBER>/changes'`

Notice how there's an extra `'` at the end of it.

The request object itself looks well formed, but the actual URL has this extra character that seems to be causing the error.

Any ideas on a solve for this? Is it a syntax error somewhere or something else?

Thank you!
