### ISSUE TITLE
Running CLI, changesets-gitlab comment produces 401 response

### ISSUE THREAD

**Issue by dave52** [un-ts/changesets-gitlab#62]
Hello -

I'm not sure if this is an actual issue, probably something I have incorrectly setup in my use of `changesets-gitlab`. If you could provide any guidance it would be appreciated though, I've tried numerous things but no luck :)

```
#gitlab-ci.yml

comment:
  stage: comment
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - npm install 
    - npx changesets-gitlab comment
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GITLAB_CI_USER_NAME: $GITLAB_CI_USER_NAME
    DEBUG_GITLAB_CREDENTIAL: 'true'
```

The problem is running the `comment` job in Gitlab produces a 401 error:
```
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/builds/zywave/content/playground/web-components/content-components/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1662857996689,
    socket: 1662857996693,
    lookup: 1662857996694,
    connect: 1662857996854,
    secureConnect: 1662857997215,
    upload: 1662857997215,
    response: 1662857997309,
    end: 1662857997312,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 4,
      dns: 1,
      tcp: 1[60](https://gitlab.com/zywave/content/playground/web-components/content-components/-/jobs/3010216532#L60),
      tls: 3[61](https://gitlab.com/zywave/content/playground/web-components/content-components/-/jobs/3010216532#L61),
      request: 0,
      firstByte: 94,
      download: 3,
      total: [62](https://gitlab.com/zywave/content/playground/web-components/content-components/-/jobs/3010216532#L62)3
    }
  },
  description: '401 Unauthorized'
}
```

I setup `GITLAB_TOKEN` as a Personal Access Token, from my own user and have them defined as project CI/CD variables. My user has `Owner` privileges on the project. As a sanity check I made another Personal Access Token and updated project variable, still hitting the same snag. Also the project is under a private group, not sure if additional config is needed for that.

If you would like more information please let me know, happy to provide, and thank you for the help!
