### ISSUE TITLE
No Changeset found comment should only appears once

### ISSUE THREAD

**Issue by devtribe** [un-ts/changesets-gitlab#63]
If there is a commit in a branch with open Merge Request and a "No Changeset found" comment is already there, the application  should not add another one. It quickly gets confusing with all the other comments.

**Comment by JounQin** [comment]
Any screenshot? Or reproduction?

**Comment by devtribe** [comment]
Sorry for forgetting the context. 

This is my gitlab ci job:
```yml
comment:
  stage: comment
  extends:
    - .init-pnpm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH != "changeset-release/main"'
  script:
    - pnpm changesets-gitlab comment # comment automatically like https://github.com/changesets/bot

.init-pnpm:
  before_script:
    - yarn global add pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

```

and here are the used versions:
```json
    "@changesets/cli": "^2.24.1",
    "changesets-gitlab": "^0.5.5",
```

And here is a screenshot.
![Bildschirmfoto 2022-09-16 um 08 06 04](https://user-images.githubusercontent.com/1044246/190568836-41f65479-be3a-4a43-8ddb-de5c72387830.png)

Thanks!
