### ISSUE TITLE
GitLab releases are no longer created by default

### ISSUE THREAD

**Issue by ciddan** [un-ts/changesets-gitlab#90]
Hey!

Recently updated from version 0.5.5 to 0.8.0 and noticed that GitLab releases were no longer being created upon deployment. Explicitly adding:
```yaml
publish:
    variables:
        INPUT_CREATE_GITLAB_RELEASES: "true"
```
fixed it, and releases are getting created again.

Looks like the value isn't defaulted to true anymore, as is stated in the docs.

https://github.com/un-ts/changesets-gitlab/blob/main/src/main.ts#L90
